{{ if $.Values.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-apps.fullname" . }}-config
  labels:
    {{- include "backend-apps.labels" . | nindent 4 }}
  {{- with .Values.configmapAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- toYaml .Values.configuration | nindent 2 }}
{{- end }}