name: golang backend CD
on:
  push:
    branches:
    - main
    paths:
    - backend-apps/golang-rest-trial/*

jobs:
  build-image:
    name: Build docker image
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          export TAGS=$(git rev-parse --short "$GITHUB_SHA")
          docker build -t akooe32/golang-rest-trial:$TAGS ./backend-apps/golang-rest-trial
  push-image:  
     name: Push docker image
     runs-on: self-hosted
     needs: build-image
     permissions:
      packages: write
      contents: read
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
      
       - name: Log in to Docker Hub
         uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Build Docker Image
         run: |
           export TAGS=$(git rev-parse --short "$GITHUB_SHA")
           docker push akooe32/golang-rest-trial:$TAGS
  
  deploy-to-kubernetes:
     name: Deploy service to k8s
     runs-on: self-hosted
     needs: push-image
     permissions:
      packages: write
      contents: read
     steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy Go apps to k8s
        run: |
          export BOT_ACCOUNT=${{ secrets.BOT_ACCOUNT }}
          export BOT_PASS=${{ secrets.BOT_PASS }}
          git config --global user.email "ryantasat32@gmail.com"
          git config --global user.name "akoe32"
          export TAGS=$(git rev-parse --short "$GITHUB_SHA")
          git clone https://$BOT_ACCOUNT:$BOT_PASS@github.com/akoe32/pintu-exam.git
          cd pintu-exam/charts/backend-apps
          yq -i ".image.tag = \"$TAGS\"" values-golang-rest-trial.yaml
          helm upgrade --install golang-rest-trial -f values-golang-rest-trial.yaml . -n golang
          git add .
          git commit -m "Bypass approval, bump up docker image golang-rest-trial using image tag $TAGS" || true
          git push -u origin main

          
        

